title: Services
fields:
  -
    handle: column_left
    field:
      collapse: false
      always_show_set_button: false
      previews: true
      buttons:
        - h3
        - bold
        - unorderedlist
        - anchor
      save_html: false
      toolbar_mode: fixed
      link_noopener: false
      link_noreferrer: false
      target_blank: false
      reading_time: false
      fullscreen: true
      allow_source: true
      enable_input_rules: true
      enable_paste_rules: true
      antlers: false
      remove_empty_nodes: false
      display: 'Column left'
      type: bard
      icon: bard
      width: 50
      listable: hidden
      instructions_position: above
      visibility: visible
      always_save: false
  -
    handle: column_right
    field:
      collapse: false
      always_show_set_button: false
      previews: true
      buttons:
        - h3
        - bold
        - unorderedlist
        - anchor
      save_html: false
      toolbar_mode: fixed
      link_noopener: false
      link_noreferrer: false
      target_blank: false
      reading_time: false
      fullscreen: true
      allow_source: true
      enable_input_rules: true
      enable_paste_rules: true
      antlers: false
      remove_empty_nodes: false
      display: 'Column right'
      type: bard
      icon: bard
      width: 50
      listable: hidden
      instructions_position: above
      visibility: visible
      always_save: false
